name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.SSH_USER }}
         password: ${{ secrets.PASSWORD }}
         port: ${{ secrets.SSH_PORT }}
         source: "*"
         target: /home/testgithubaction/public_html
         overwrite: true
