name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
        script: |
          cd /home/testgithubaction/public_html && git pull origin main
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.SSH_USER }}
         password: ${{ secrets.PASSWORD }}
         port: ${{ secrets.SSH_PORT }}
         source: "src/*"
         target: /home/testgithubaction/public_html
         
         
      
